services:
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - BACKEND_URL=http://localhost:8080
      - BACKEND_WS_URL=ws://localhost:8080/agent
      - API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - stars-network

  backend:
    platform: linux/amd64
    build:
      context: ./backend-agent
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend-agent/.env
    networks:
      - stars-network
    volumes:
      - stars-backend-db:/data

networks:
  stars-network:
    driver: bridge

volumes:
  stars-backend-db:
