name: Test backend installation

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.py'
      - '**.txt'
  workflow_dispatch:

permissions:
    checks: read
    contents: read

jobs:
    installation:
        name: Test backend installation
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
                token: ${{ secrets.GITHUB_TOKEN }}
                cache: 'pip'
                cache-dependency-path: backend-agent/requirements.txt
            - run: pip install -r backend-agent/requirements.txt

            - name: Start server and check health
              run: |
                cd backend-agent
                DISABLE_AGENT=1 DB_PATH=${RUNNER_TEMP}/data.db python main.py > server.log 2>&1 &
                for i in {1..20}; do
                  sleep 1
                  status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health || true)
                  if [ "$status" -eq 200 ]; then
                    echo "Health check succeeded"
                    cat server.log
                    exit 0
                  fi
                done
                echo "Health check failed after waiting"
                cat server.log
                exit 1
