name: AI-assisted
on:
  pull_request_target:
    types: [ready_for_review, opened, reopened]

jobs:
  summary:
    name: PR Summary
    runs-on: [ubuntu-latest]
    steps:
      - uses: SAP/ai-assisted-github-actions/pr-summary@v3
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: gpt-4o
          exclude-files: package-lock.json, uv.lock
  review:
    name: PR Review
    runs-on: [ubuntu-latest]
    steps:
      - uses: SAP/ai-assisted-github-actions/pr-review@v3
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: anthropic--claude-4-sonnet
          exclude-files: package-lock.json, uv.lock
          footer-text: |
            ---
            > Always critique what AI says. Do not let AI replace YOUR I.
